import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/app/components/navbar/Navbar";
import Footer from "@/app/components/footer/Footer";
import HamburgerMenu from "@/app/components/navbar/HamburgerMenu";
import Logo from "@/app/components/navbar/logo";
import React from "react";
import Cart from "@/app/components/navbar/cart";
import "./firebase/firebaseConfig";
import {CartProvider} from "@/app/context/CartContext";
import KullaniciIcon from "@/app/components/navbar/KullaniciIcon";
import {AuthProvider} from "@/app/context/AuthContext";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Nadire'n",
    description: "Generated by create next app",

};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <div className="flex flex-col min-h-screen gap-6">
                    <CartProvider>
                        <AuthProvider>
                            <Navbar/>
                            <Logo />
                            <Cart/>
                            <KullaniciIcon/>
                            <HamburgerMenu/>
                            <main className="flex-grow">{children}</main>
                            <Footer/>
                        </AuthProvider>
                    </CartProvider>
                </div>
            </body>
        </html>
    );
}
